[global.databases]
mydb = { url = "sqlite.db" }

[development]
address = "localhost"
port = 8080
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "thismustbeafixedsizesecretkeyofprecisely44B="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8080
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "thismustbeafixedsizesecretkeyofprecisely44B="
limits = { forms = 32768 }
